# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae6eca02631bf5209da85faa8983a1d8f690b0acd5e73b0f055c32cde7ad7d3994c5814bc9596add460083a2ed9868e19d4a6c0269ad43acbdcc5b777e01cae8

test:
  secret_key_base: b1b2ed1c2a9c79d73bf1a9b22e8b8be42058d59727af549d875e83055c5d2b0697274a838188b56b08669d1149c79cae31be448365b25533e9c6c86ffe7e520d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
